source 'https://rubygems.org'

gem 'rspec'
gem 'sinatra'
gem 'colorize'
gem 'rest-client'
gem 'whois'
gem 'nokogiri'
gem 'geocoder'
gem 'phonelib'
gem 'public_suffix'
gem 'launchy'
gem 'dnsruby', '~> 1.72.4'
gem 'terminal-table'
gem 'ruby-progressbar'
gem 'mini_exiftool'
gem 'selenium-webdriver'
gem 'open-uri'