name: Ruby CI & Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
      - 'cm*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' || github.ref_type == 'tag'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/cm') || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
